//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurum.Wpf.ServicoAurum {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cartao", Namespace="http://schemas.datacontract.org/2004/07/ServicoAurum.Entidades")]
    [System.SerializableAttribute()]
    public partial class Cartao : Aurum.Wpf.ServicoAurum.Entidade {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodCartaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodContaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PossuiAdicionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneSacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ValidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte VencimentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((this.AtivoField.Equals(value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodCartao {
            get {
                return this.CodCartaoField;
            }
            set {
                if ((this.CodCartaoField.Equals(value) != true)) {
                    this.CodCartaoField = value;
                    this.RaisePropertyChanged("CodCartao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodConta {
            get {
                return this.CodContaField;
            }
            set {
                if ((this.CodContaField.Equals(value) != true)) {
                    this.CodContaField = value;
                    this.RaisePropertyChanged("CodConta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PossuiAdicional {
            get {
                return this.PossuiAdicionalField;
            }
            set {
                if ((this.PossuiAdicionalField.Equals(value) != true)) {
                    this.PossuiAdicionalField = value;
                    this.RaisePropertyChanged("PossuiAdicional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneSac {
            get {
                return this.TelefoneSacField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneSacField, value) != true)) {
                    this.TelefoneSacField = value;
                    this.RaisePropertyChanged("TelefoneSac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titular {
            get {
                return this.TitularField;
            }
            set {
                if ((object.ReferenceEquals(this.TitularField, value) != true)) {
                    this.TitularField = value;
                    this.RaisePropertyChanged("Titular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Validade {
            get {
                return this.ValidadeField;
            }
            set {
                if ((this.ValidadeField.Equals(value) != true)) {
                    this.ValidadeField = value;
                    this.RaisePropertyChanged("Validade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Vencimento {
            get {
                return this.VencimentoField;
            }
            set {
                if ((this.VencimentoField.Equals(value) != true)) {
                    this.VencimentoField = value;
                    this.RaisePropertyChanged("Vencimento");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entidade", Namespace="http://schemas.datacontract.org/2004/07/ServicoAurum.Dados")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Aurum.Wpf.ServicoAurum.Conta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Aurum.Wpf.ServicoAurum.Cartao))]
    public partial class Entidade : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Conta", Namespace="http://schemas.datacontract.org/2004/07/ServicoAurum.Entidades")]
    [System.SerializableAttribute()]
    public partial class Conta : Aurum.Wpf.ServicoAurum.Entidade {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgenciaContaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodContaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgenciaConta {
            get {
                return this.AgenciaContaField;
            }
            set {
                if ((object.ReferenceEquals(this.AgenciaContaField, value) != true)) {
                    this.AgenciaContaField = value;
                    this.RaisePropertyChanged("AgenciaConta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((this.AtivoField.Equals(value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Banco {
            get {
                return this.BancoField;
            }
            set {
                if ((object.ReferenceEquals(this.BancoField, value) != true)) {
                    this.BancoField = value;
                    this.RaisePropertyChanged("Banco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodConta {
            get {
                return this.CodContaField;
            }
            set {
                if ((this.CodContaField.Equals(value) != true)) {
                    this.CodContaField = value;
                    this.RaisePropertyChanged("CodConta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoAurum.IAurum")]
    public interface IAurum {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAurum/ListarCartao", ReplyAction="http://tempuri.org/IAurum/ListarCartaoResponse")]
        Aurum.Wpf.ServicoAurum.Cartao[] ListarCartao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAurum/SalvarCartao", ReplyAction="http://tempuri.org/IAurum/SalvarCartaoResponse")]
        int SalvarCartao(System.Nullable<int> codCartao, bool ativo, System.Nullable<int> codConta, string descricao, string numero, string titular, byte vencimento, System.Nullable<System.DateTime> validade, bool possuiAdicional, string telefoneSac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAurum/ExcluirCartao", ReplyAction="http://tempuri.org/IAurum/ExcluirCartaoResponse")]
        void ExcluirCartao(int codCartao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAurum/ListarConta", ReplyAction="http://tempuri.org/IAurum/ListarContaResponse")]
        Aurum.Wpf.ServicoAurum.Conta[] ListarConta();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAurumChannel : Aurum.Wpf.ServicoAurum.IAurum, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AurumClient : System.ServiceModel.ClientBase<Aurum.Wpf.ServicoAurum.IAurum>, Aurum.Wpf.ServicoAurum.IAurum {
        
        public AurumClient() {
        }
        
        public AurumClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AurumClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AurumClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AurumClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Aurum.Wpf.ServicoAurum.Cartao[] ListarCartao() {
            return base.Channel.ListarCartao();
        }
        
        public int SalvarCartao(System.Nullable<int> codCartao, bool ativo, System.Nullable<int> codConta, string descricao, string numero, string titular, byte vencimento, System.Nullable<System.DateTime> validade, bool possuiAdicional, string telefoneSac) {
            return base.Channel.SalvarCartao(codCartao, ativo, codConta, descricao, numero, titular, vencimento, validade, possuiAdicional, telefoneSac);
        }
        
        public void ExcluirCartao(int codCartao) {
            base.Channel.ExcluirCartao(codCartao);
        }
        
        public Aurum.Wpf.ServicoAurum.Conta[] ListarConta() {
            return base.Channel.ListarConta();
        }
    }
}
