// <auto-generated />
namespace Aurum.Modelo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CarteiraVinculada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CarteiraVinculada));
        
        string IMigrationMetadata.Id
        {
            get { return "201405211157416_CarteiraVinculada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
