//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Aurum", "FK_Cartao_Conta", "Conta", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Aurum.Wpf.BD.Conta), "Cartao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aurum.Wpf.BD.Cartao), true)]
[assembly: EdmRelationshipAttribute("Aurum", "FK_Movimento_Cartao", "Cartao", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Aurum.Wpf.BD.Cartao), "Movimento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aurum.Wpf.BD.Movimento), true)]
[assembly: EdmRelationshipAttribute("Aurum", "FK_Taxa_Cartao", "Cartao", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Aurum.Wpf.BD.Cartao), "Taxa", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aurum.Wpf.BD.Taxa), true)]
[assembly: EdmRelationshipAttribute("Aurum", "FK_Movimento_Categoria", "Categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Aurum.Wpf.BD.Categoria), "Movimento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aurum.Wpf.BD.Movimento), true)]
[assembly: EdmRelationshipAttribute("Aurum", "FK_Movimento_Conta", "Conta", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Aurum.Wpf.BD.Conta), "Movimento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aurum.Wpf.BD.Movimento), true)]
[assembly: EdmRelationshipAttribute("Aurum", "FK_Taxa_Conta", "Conta", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Aurum.Wpf.BD.Conta), "Taxa", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aurum.Wpf.BD.Taxa), true)]
[assembly: EdmRelationshipAttribute("Aurum", "FK_MovimentoPrimeiraParcela", "Movimento", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Aurum.Wpf.BD.Movimento), "Movimento1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aurum.Wpf.BD.Movimento), true)]
[assembly: EdmRelationshipAttribute("Aurum", "FK_MovimentoReserva", "Movimento", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Aurum.Wpf.BD.Movimento), "Movimento1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aurum.Wpf.BD.Movimento), true)]
[assembly: EdmRelationshipAttribute("Aurum", "FK_MovimentoDescricao", "MovimentoDescricao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Aurum.Wpf.BD.MovimentoDescricao), "Movimento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aurum.Wpf.BD.Movimento), true)]

#endregion

namespace Aurum.Wpf.BD
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BancoDados : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BancoDados object using the connection string found in the 'BancoDados' section of the application configuration file.
        /// </summary>
        public BancoDados() : base("name=BancoDados", "BancoDados")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BancoDados object.
        /// </summary>
        public BancoDados(string connectionString) : base(connectionString, "BancoDados")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BancoDados object.
        /// </summary>
        public BancoDados(EntityConnection connection) : base(connection, "BancoDados")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cartao> Cartao
        {
            get
            {
                if ((_Cartao == null))
                {
                    _Cartao = base.CreateObjectSet<Cartao>("Cartao");
                }
                return _Cartao;
            }
        }
        private ObjectSet<Cartao> _Cartao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Categoria> Categoria
        {
            get
            {
                if ((_Categoria == null))
                {
                    _Categoria = base.CreateObjectSet<Categoria>("Categoria");
                }
                return _Categoria;
            }
        }
        private ObjectSet<Categoria> _Categoria;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Conta> Conta
        {
            get
            {
                if ((_Conta == null))
                {
                    _Conta = base.CreateObjectSet<Conta>("Conta");
                }
                return _Conta;
            }
        }
        private ObjectSet<Conta> _Conta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Movimento> Movimento
        {
            get
            {
                if ((_Movimento == null))
                {
                    _Movimento = base.CreateObjectSet<Movimento>("Movimento");
                }
                return _Movimento;
            }
        }
        private ObjectSet<Movimento> _Movimento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MovimentoDescricao> MovimentoDescricao
        {
            get
            {
                if ((_MovimentoDescricao == null))
                {
                    _MovimentoDescricao = base.CreateObjectSet<MovimentoDescricao>("MovimentoDescricao");
                }
                return _MovimentoDescricao;
            }
        }
        private ObjectSet<MovimentoDescricao> _MovimentoDescricao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Taxa> Taxa
        {
            get
            {
                if ((_Taxa == null))
                {
                    _Taxa = base.CreateObjectSet<Taxa>("Taxa");
                }
                return _Taxa;
            }
        }
        private ObjectSet<Taxa> _Taxa;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cartao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCartao(Cartao cartao)
        {
            base.AddObject("Cartao", cartao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categoria EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoria(Categoria categoria)
        {
            base.AddObject("Categoria", categoria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Conta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConta(Conta conta)
        {
            base.AddObject("Conta", conta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Movimento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovimento(Movimento movimento)
        {
            base.AddObject("Movimento", movimento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MovimentoDescricao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovimentoDescricao(MovimentoDescricao movimentoDescricao)
        {
            base.AddObject("MovimentoDescricao", movimentoDescricao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Taxa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTaxa(Taxa taxa)
        {
            base.AddObject("Taxa", taxa);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Aurum", Name="Cartao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cartao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cartao object.
        /// </summary>
        /// <param name="codCartao">Initial value of the CodCartao property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="numero">Initial value of the Numero property.</param>
        /// <param name="titular">Initial value of the Titular property.</param>
        /// <param name="vencimento">Initial value of the Vencimento property.</param>
        /// <param name="possuiAdicional">Initial value of the PossuiAdicional property.</param>
        public static Cartao CreateCartao(global::System.Int32 codCartao, global::System.Boolean ativo, global::System.String descricao, global::System.String numero, global::System.String titular, global::System.Byte vencimento, global::System.Boolean possuiAdicional)
        {
            Cartao cartao = new Cartao();
            cartao.CodCartao = codCartao;
            cartao.Ativo = ativo;
            cartao.Descricao = descricao;
            cartao.Numero = numero;
            cartao.Titular = titular;
            cartao.Vencimento = vencimento;
            cartao.PossuiAdicional = possuiAdicional;
            return cartao;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodCartao
        {
            get
            {
                return _CodCartao;
            }
            set
            {
                if (_CodCartao != value)
                {
                    OnCodCartaoChanging(value);
                    ReportPropertyChanging("CodCartao");
                    _CodCartao = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodCartao");
                    OnCodCartaoChanged();
                }
            }
        }
        private global::System.Int32 _CodCartao;
        partial void OnCodCartaoChanging(global::System.Int32 value);
        partial void OnCodCartaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CodConta
        {
            get
            {
                return _CodConta;
            }
            set
            {
                OnCodContaChanging(value);
                ReportPropertyChanging("CodConta");
                _CodConta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodConta");
                OnCodContaChanged();
            }
        }
        private Nullable<global::System.Int32> _CodConta;
        partial void OnCodContaChanging(Nullable<global::System.Int32> value);
        partial void OnCodContaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.String _Numero;
        partial void OnNumeroChanging(global::System.String value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titular
        {
            get
            {
                return _Titular;
            }
            set
            {
                OnTitularChanging(value);
                ReportPropertyChanging("Titular");
                _Titular = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titular");
                OnTitularChanged();
            }
        }
        private global::System.String _Titular;
        partial void OnTitularChanging(global::System.String value);
        partial void OnTitularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Vencimento
        {
            get
            {
                return _Vencimento;
            }
            set
            {
                OnVencimentoChanging(value);
                ReportPropertyChanging("Vencimento");
                _Vencimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vencimento");
                OnVencimentoChanged();
            }
        }
        private global::System.Byte _Vencimento;
        partial void OnVencimentoChanging(global::System.Byte value);
        partial void OnVencimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Validade
        {
            get
            {
                return _Validade;
            }
            set
            {
                OnValidadeChanging(value);
                ReportPropertyChanging("Validade");
                _Validade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Validade");
                OnValidadeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Validade;
        partial void OnValidadeChanging(Nullable<global::System.DateTime> value);
        partial void OnValidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PossuiAdicional
        {
            get
            {
                return _PossuiAdicional;
            }
            set
            {
                OnPossuiAdicionalChanging(value);
                ReportPropertyChanging("PossuiAdicional");
                _PossuiAdicional = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PossuiAdicional");
                OnPossuiAdicionalChanged();
            }
        }
        private global::System.Boolean _PossuiAdicional;
        partial void OnPossuiAdicionalChanging(global::System.Boolean value);
        partial void OnPossuiAdicionalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelefoneSac
        {
            get
            {
                return _TelefoneSac;
            }
            set
            {
                OnTelefoneSacChanging(value);
                ReportPropertyChanging("TelefoneSac");
                _TelefoneSac = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelefoneSac");
                OnTelefoneSacChanged();
            }
        }
        private global::System.String _TelefoneSac;
        partial void OnTelefoneSacChanging(global::System.String value);
        partial void OnTelefoneSacChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_Cartao_Conta", "Conta")]
        public Conta Conta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("Aurum.FK_Cartao_Conta", "Conta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("Aurum.FK_Cartao_Conta", "Conta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Conta> ContaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("Aurum.FK_Cartao_Conta", "Conta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Conta>("Aurum.FK_Cartao_Conta", "Conta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_Movimento_Cartao", "Movimento")]
        public EntityCollection<Movimento> Movimentos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Movimento>("Aurum.FK_Movimento_Cartao", "Movimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Movimento>("Aurum.FK_Movimento_Cartao", "Movimento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_Taxa_Cartao", "Taxa")]
        public EntityCollection<Taxa> Taxas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Taxa>("Aurum.FK_Taxa_Cartao", "Taxa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Taxa>("Aurum.FK_Taxa_Cartao", "Taxa", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Aurum", Name="Categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categoria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Categoria object.
        /// </summary>
        /// <param name="codCategoria">Initial value of the CodCategoria property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Categoria CreateCategoria(global::System.Int32 codCategoria, global::System.Boolean ativo, global::System.String descricao)
        {
            Categoria categoria = new Categoria();
            categoria.CodCategoria = codCategoria;
            categoria.Ativo = ativo;
            categoria.Descricao = descricao;
            return categoria;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodCategoria
        {
            get
            {
                return _CodCategoria;
            }
            set
            {
                if (_CodCategoria != value)
                {
                    OnCodCategoriaChanging(value);
                    ReportPropertyChanging("CodCategoria");
                    _CodCategoria = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodCategoria");
                    OnCodCategoriaChanged();
                }
            }
        }
        private global::System.Int32 _CodCategoria;
        partial void OnCodCategoriaChanging(global::System.Int32 value);
        partial void OnCodCategoriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_Movimento_Categoria", "Movimento")]
        public EntityCollection<Movimento> Movimentos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Movimento>("Aurum.FK_Movimento_Categoria", "Movimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Movimento>("Aurum.FK_Movimento_Categoria", "Movimento", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Aurum", Name="Conta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Conta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Conta object.
        /// </summary>
        /// <param name="codConta">Initial value of the CodConta property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        /// <param name="banco">Initial value of the Banco property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        /// <param name="agenciaConta">Initial value of the AgenciaConta property.</param>
        public static Conta CreateConta(global::System.Int32 codConta, global::System.Boolean ativo, global::System.String banco, global::System.Byte tipo, global::System.String agenciaConta)
        {
            Conta conta = new Conta();
            conta.CodConta = codConta;
            conta.Ativo = ativo;
            conta.Banco = banco;
            conta.Tipo = tipo;
            conta.AgenciaConta = agenciaConta;
            return conta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodConta
        {
            get
            {
                return _CodConta;
            }
            set
            {
                if (_CodConta != value)
                {
                    OnCodContaChanging(value);
                    ReportPropertyChanging("CodConta");
                    _CodConta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodConta");
                    OnCodContaChanged();
                }
            }
        }
        private global::System.Int32 _CodConta;
        partial void OnCodContaChanging(global::System.Int32 value);
        partial void OnCodContaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Banco
        {
            get
            {
                return _Banco;
            }
            set
            {
                OnBancoChanging(value);
                ReportPropertyChanging("Banco");
                _Banco = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Banco");
                OnBancoChanged();
            }
        }
        private global::System.String _Banco;
        partial void OnBancoChanging(global::System.String value);
        partial void OnBancoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.Byte _Tipo;
        partial void OnTipoChanging(global::System.Byte value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AgenciaConta
        {
            get
            {
                return _AgenciaConta;
            }
            set
            {
                OnAgenciaContaChanging(value);
                ReportPropertyChanging("AgenciaConta");
                _AgenciaConta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AgenciaConta");
                OnAgenciaContaChanged();
            }
        }
        private global::System.String _AgenciaConta;
        partial void OnAgenciaContaChanging(global::System.String value);
        partial void OnAgenciaContaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_Cartao_Conta", "Cartao")]
        public EntityCollection<Cartao> Cartoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cartao>("Aurum.FK_Cartao_Conta", "Cartao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cartao>("Aurum.FK_Cartao_Conta", "Cartao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_Movimento_Conta", "Movimento")]
        public EntityCollection<Movimento> Movimentos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Movimento>("Aurum.FK_Movimento_Conta", "Movimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Movimento>("Aurum.FK_Movimento_Conta", "Movimento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_Taxa_Conta", "Taxa")]
        public EntityCollection<Taxa> Taxas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Taxa>("Aurum.FK_Taxa_Conta", "Taxa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Taxa>("Aurum.FK_Taxa_Conta", "Taxa", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Aurum", Name="Movimento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Movimento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Movimento object.
        /// </summary>
        /// <param name="codMovimento">Initial value of the CodMovimento property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        /// <param name="dataHoraInclusao">Initial value of the DataHoraInclusao property.</param>
        /// <param name="mesAno">Initial value of the MesAno property.</param>
        /// <param name="codMovimentoDescricao">Initial value of the CodMovimentoDescricao property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        /// <param name="reserva">Initial value of the Reserva property.</param>
        public static Movimento CreateMovimento(global::System.Int32 codMovimento, global::System.Boolean ativo, global::System.DateTime dataHoraInclusao, global::System.DateTime mesAno, global::System.Int32 codMovimentoDescricao, global::System.Int32 valor, global::System.Boolean reserva)
        {
            Movimento movimento = new Movimento();
            movimento.CodMovimento = codMovimento;
            movimento.Ativo = ativo;
            movimento.DataHoraInclusao = dataHoraInclusao;
            movimento.MesAno = mesAno;
            movimento.CodMovimentoDescricao = codMovimentoDescricao;
            movimento.Valor = valor;
            movimento.Reserva = reserva;
            return movimento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodMovimento
        {
            get
            {
                return _CodMovimento;
            }
            set
            {
                if (_CodMovimento != value)
                {
                    OnCodMovimentoChanging(value);
                    ReportPropertyChanging("CodMovimento");
                    _CodMovimento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodMovimento");
                    OnCodMovimentoChanged();
                }
            }
        }
        private global::System.Int32 _CodMovimento;
        partial void OnCodMovimentoChanging(global::System.Int32 value);
        partial void OnCodMovimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataHoraInclusao
        {
            get
            {
                return _DataHoraInclusao;
            }
            set
            {
                OnDataHoraInclusaoChanging(value);
                ReportPropertyChanging("DataHoraInclusao");
                _DataHoraInclusao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataHoraInclusao");
                OnDataHoraInclusaoChanged();
            }
        }
        private global::System.DateTime _DataHoraInclusao;
        partial void OnDataHoraInclusaoChanging(global::System.DateTime value);
        partial void OnDataHoraInclusaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(Nullable<global::System.DateTime> value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MesAno
        {
            get
            {
                return _MesAno;
            }
            set
            {
                OnMesAnoChanging(value);
                ReportPropertyChanging("MesAno");
                _MesAno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MesAno");
                OnMesAnoChanged();
            }
        }
        private global::System.DateTime _MesAno;
        partial void OnMesAnoChanging(global::System.DateTime value);
        partial void OnMesAnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodMovimentoDescricao
        {
            get
            {
                return _CodMovimentoDescricao;
            }
            set
            {
                OnCodMovimentoDescricaoChanging(value);
                ReportPropertyChanging("CodMovimentoDescricao");
                _CodMovimentoDescricao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodMovimentoDescricao");
                OnCodMovimentoDescricaoChanged();
            }
        }
        private global::System.Int32 _CodMovimentoDescricao;
        partial void OnCodMovimentoDescricaoChanging(global::System.Int32 value);
        partial void OnCodMovimentoDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CodCategoria
        {
            get
            {
                return _CodCategoria;
            }
            set
            {
                OnCodCategoriaChanging(value);
                ReportPropertyChanging("CodCategoria");
                _CodCategoria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodCategoria");
                OnCodCategoriaChanged();
            }
        }
        private Nullable<global::System.Int32> _CodCategoria;
        partial void OnCodCategoriaChanging(Nullable<global::System.Int32> value);
        partial void OnCodCategoriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Int32 _Valor;
        partial void OnValorChanging(global::System.Int32 value);
        partial void OnValorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CodConta
        {
            get
            {
                return _CodConta;
            }
            set
            {
                OnCodContaChanging(value);
                ReportPropertyChanging("CodConta");
                _CodConta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodConta");
                OnCodContaChanged();
            }
        }
        private Nullable<global::System.Int32> _CodConta;
        partial void OnCodContaChanging(Nullable<global::System.Int32> value);
        partial void OnCodContaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CodCartao
        {
            get
            {
                return _CodCartao;
            }
            set
            {
                OnCodCartaoChanging(value);
                ReportPropertyChanging("CodCartao");
                _CodCartao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodCartao");
                OnCodCartaoChanged();
            }
        }
        private Nullable<global::System.Int32> _CodCartao;
        partial void OnCodCartaoChanging(Nullable<global::System.Int32> value);
        partial void OnCodCartaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Reserva
        {
            get
            {
                return _Reserva;
            }
            set
            {
                OnReservaChanging(value);
                ReportPropertyChanging("Reserva");
                _Reserva = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Reserva");
                OnReservaChanged();
            }
        }
        private global::System.Boolean _Reserva;
        partial void OnReservaChanging(global::System.Boolean value);
        partial void OnReservaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CodMovimentoReserva
        {
            get
            {
                return _CodMovimentoReserva;
            }
            set
            {
                OnCodMovimentoReservaChanging(value);
                ReportPropertyChanging("CodMovimentoReserva");
                _CodMovimentoReserva = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodMovimentoReserva");
                OnCodMovimentoReservaChanged();
            }
        }
        private Nullable<global::System.Int32> _CodMovimentoReserva;
        partial void OnCodMovimentoReservaChanging(Nullable<global::System.Int32> value);
        partial void OnCodMovimentoReservaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CodMovimentoPrimeiraParcela
        {
            get
            {
                return _CodMovimentoPrimeiraParcela;
            }
            set
            {
                OnCodMovimentoPrimeiraParcelaChanging(value);
                ReportPropertyChanging("CodMovimentoPrimeiraParcela");
                _CodMovimentoPrimeiraParcela = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodMovimentoPrimeiraParcela");
                OnCodMovimentoPrimeiraParcelaChanged();
            }
        }
        private Nullable<global::System.Int32> _CodMovimentoPrimeiraParcela;
        partial void OnCodMovimentoPrimeiraParcelaChanging(Nullable<global::System.Int32> value);
        partial void OnCodMovimentoPrimeiraParcelaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacao
        {
            get
            {
                return _Observacao;
            }
            set
            {
                OnObservacaoChanging(value);
                ReportPropertyChanging("Observacao");
                _Observacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacao");
                OnObservacaoChanged();
            }
        }
        private global::System.String _Observacao;
        partial void OnObservacaoChanging(global::System.String value);
        partial void OnObservacaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_Movimento_Cartao", "Cartao")]
        public Cartao Cartao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cartao>("Aurum.FK_Movimento_Cartao", "Cartao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cartao>("Aurum.FK_Movimento_Cartao", "Cartao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cartao> CartaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cartao>("Aurum.FK_Movimento_Cartao", "Cartao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cartao>("Aurum.FK_Movimento_Cartao", "Cartao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_Movimento_Categoria", "Categoria")]
        public Categoria Categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("Aurum.FK_Movimento_Categoria", "Categoria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("Aurum.FK_Movimento_Categoria", "Categoria").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categoria> CategoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("Aurum.FK_Movimento_Categoria", "Categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categoria>("Aurum.FK_Movimento_Categoria", "Categoria", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_Movimento_Conta", "Conta")]
        public Conta Conta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("Aurum.FK_Movimento_Conta", "Conta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("Aurum.FK_Movimento_Conta", "Conta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Conta> ContaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("Aurum.FK_Movimento_Conta", "Conta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Conta>("Aurum.FK_Movimento_Conta", "Conta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_MovimentoPrimeiraParcela", "Movimento1")]
        public EntityCollection<Movimento> MovimentosDestaPrimeiraParcela
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Movimento>("Aurum.FK_MovimentoPrimeiraParcela", "Movimento1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Movimento>("Aurum.FK_MovimentoPrimeiraParcela", "Movimento1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_MovimentoPrimeiraParcela", "Movimento")]
        public Movimento MovimentoPrimeiraParcela
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movimento>("Aurum.FK_MovimentoPrimeiraParcela", "Movimento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movimento>("Aurum.FK_MovimentoPrimeiraParcela", "Movimento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Movimento> MovimentoPrimeiraParcelaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movimento>("Aurum.FK_MovimentoPrimeiraParcela", "Movimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Movimento>("Aurum.FK_MovimentoPrimeiraParcela", "Movimento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_MovimentoReserva", "Movimento1")]
        public EntityCollection<Movimento> MovimentosDestaReserva
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Movimento>("Aurum.FK_MovimentoReserva", "Movimento1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Movimento>("Aurum.FK_MovimentoReserva", "Movimento1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_MovimentoReserva", "Movimento")]
        public Movimento MovimentoReserva
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movimento>("Aurum.FK_MovimentoReserva", "Movimento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movimento>("Aurum.FK_MovimentoReserva", "Movimento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Movimento> MovimentoReservaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movimento>("Aurum.FK_MovimentoReserva", "Movimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Movimento>("Aurum.FK_MovimentoReserva", "Movimento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_MovimentoDescricao", "MovimentoDescricao")]
        public MovimentoDescricao MovimentoDescricao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovimentoDescricao>("Aurum.FK_MovimentoDescricao", "MovimentoDescricao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovimentoDescricao>("Aurum.FK_MovimentoDescricao", "MovimentoDescricao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MovimentoDescricao> MovimentoDescricaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovimentoDescricao>("Aurum.FK_MovimentoDescricao", "MovimentoDescricao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MovimentoDescricao>("Aurum.FK_MovimentoDescricao", "MovimentoDescricao", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Aurum", Name="MovimentoDescricao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MovimentoDescricao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MovimentoDescricao object.
        /// </summary>
        /// <param name="codMovimentoDescricao">Initial value of the CodMovimentoDescricao property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static MovimentoDescricao CreateMovimentoDescricao(global::System.Int32 codMovimentoDescricao, global::System.String descricao)
        {
            MovimentoDescricao movimentoDescricao = new MovimentoDescricao();
            movimentoDescricao.CodMovimentoDescricao = codMovimentoDescricao;
            movimentoDescricao.Descricao = descricao;
            return movimentoDescricao;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodMovimentoDescricao
        {
            get
            {
                return _CodMovimentoDescricao;
            }
            set
            {
                if (_CodMovimentoDescricao != value)
                {
                    OnCodMovimentoDescricaoChanging(value);
                    ReportPropertyChanging("CodMovimentoDescricao");
                    _CodMovimentoDescricao = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodMovimentoDescricao");
                    OnCodMovimentoDescricaoChanged();
                }
            }
        }
        private global::System.Int32 _CodMovimentoDescricao;
        partial void OnCodMovimentoDescricaoChanging(global::System.Int32 value);
        partial void OnCodMovimentoDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_MovimentoDescricao", "Movimento")]
        public EntityCollection<Movimento> Movimentos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Movimento>("Aurum.FK_MovimentoDescricao", "Movimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Movimento>("Aurum.FK_MovimentoDescricao", "Movimento", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Aurum", Name="Taxa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Taxa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Taxa object.
        /// </summary>
        /// <param name="codTaxa">Initial value of the CodTaxa property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        public static Taxa CreateTaxa(global::System.Int32 codTaxa, global::System.Boolean ativo, global::System.Int32 valor)
        {
            Taxa taxa = new Taxa();
            taxa.CodTaxa = codTaxa;
            taxa.Ativo = ativo;
            taxa.Valor = valor;
            return taxa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodTaxa
        {
            get
            {
                return _CodTaxa;
            }
            set
            {
                if (_CodTaxa != value)
                {
                    OnCodTaxaChanging(value);
                    ReportPropertyChanging("CodTaxa");
                    _CodTaxa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodTaxa");
                    OnCodTaxaChanged();
                }
            }
        }
        private global::System.Int32 _CodTaxa;
        partial void OnCodTaxaChanging(global::System.Int32 value);
        partial void OnCodTaxaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CodConta
        {
            get
            {
                return _CodConta;
            }
            set
            {
                OnCodContaChanging(value);
                ReportPropertyChanging("CodConta");
                _CodConta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodConta");
                OnCodContaChanged();
            }
        }
        private Nullable<global::System.Int32> _CodConta;
        partial void OnCodContaChanging(Nullable<global::System.Int32> value);
        partial void OnCodContaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CodCartao
        {
            get
            {
                return _CodCartao;
            }
            set
            {
                OnCodCartaoChanging(value);
                ReportPropertyChanging("CodCartao");
                _CodCartao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CodCartao");
                OnCodCartaoChanged();
            }
        }
        private Nullable<global::System.Int32> _CodCartao;
        partial void OnCodCartaoChanging(Nullable<global::System.Int32> value);
        partial void OnCodCartaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Int32 _Valor;
        partial void OnValorChanging(global::System.Int32 value);
        partial void OnValorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Validade
        {
            get
            {
                return _Validade;
            }
            set
            {
                OnValidadeChanging(value);
                ReportPropertyChanging("Validade");
                _Validade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Validade");
                OnValidadeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Validade;
        partial void OnValidadeChanging(Nullable<global::System.DateTime> value);
        partial void OnValidadeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_Taxa_Cartao", "Cartao")]
        public Cartao Cartao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cartao>("Aurum.FK_Taxa_Cartao", "Cartao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cartao>("Aurum.FK_Taxa_Cartao", "Cartao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cartao> CartaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cartao>("Aurum.FK_Taxa_Cartao", "Cartao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cartao>("Aurum.FK_Taxa_Cartao", "Cartao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Aurum", "FK_Taxa_Conta", "Conta")]
        public Conta Conta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("Aurum.FK_Taxa_Conta", "Conta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("Aurum.FK_Taxa_Conta", "Conta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Conta> ContaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("Aurum.FK_Taxa_Conta", "Conta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Conta>("Aurum.FK_Taxa_Conta", "Conta", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
