//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurum.AcessoDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cartao()
        {
            this.Movimentacoes = new HashSet<Movimentacao>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> IdConta { get; set; }
    
        public virtual Conta Conta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimentacao> Movimentacoes { get; set; }
    }
}
