//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurum.AcessoDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimentacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movimentacao()
        {
            this.MovimentacoesProximasParcelas = new HashSet<Movimentacao>();
        }
    
        public System.Guid Id { get; set; }
        public int IdCategoria { get; set; }
        public Nullable<int> IdConta { get; set; }
        public Nullable<int> IdCartao { get; set; }
        public System.DateTime Data { get; set; }
        public string Descricao { get; set; }
        public decimal Valor { get; set; }
        public bool Efetivada { get; set; }
        public System.DateTime DataHoraInclusao { get; set; }
        public Nullable<System.Guid> IdMovimentacaoPrimeiraParcela { get; set; }
        public Nullable<short> NumeroParcela { get; set; }
        public Nullable<short> TotalParcelas { get; set; }
        public string Observacao { get; set; }
    
        public virtual Cartao Cartao { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Conta Conta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimentacao> MovimentacoesProximasParcelas { get; set; }
        public virtual Movimentacao MovimentacaoPrimeiraParcela { get; set; }
    }
}
