ALTER TABLE [dbo].[Conta]
    ADD CONSTRAINT [PK_Conta] PRIMARY KEY CLUSTERED ([CodConta] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

