ALTER TABLE [dbo].[Movimento]
    ADD CONSTRAINT [PK_Movimento] PRIMARY KEY CLUSTERED ([CodMovimento] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

