ALTER TABLE [dbo].[Taxa]
    ADD CONSTRAINT [PK_Taxa] PRIMARY KEY CLUSTERED ([CodTaxa] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

