ALTER TABLE [dbo].[MovimentoDescricao]
    ADD CONSTRAINT [PK_MovimentoDescricao] PRIMARY KEY CLUSTERED ([CodMovimentoDescricao] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

